import Head from "next/head";
import Image from "next/image";
import Experience from "../components/Experience.jsx";
import Projects from "../components/Projects.jsx";
import TechStack from "../components/TechStack.jsx";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Madden Lockin Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Madden Lockin</h1>
                <div className={styles.layout}>
                    <TechStack />
                    <Experience />
                    <Projects />
                </div>
            </main>

            <footer className={styles.footer}></footer>
        </div>
    );
}
